lib/yform/validate/existintable.php

$db->escape zu $db->escapeIdentifier

---

plugins/geo/pages/index.php

Müsste https://github.com/yakamara/redaxo_yform/issues/92 beheben. Ungetestet.

geocode-Plugin: Google Javascript API http:// -> //

---

plugins/manager/boot.php
plugins/manager/install.php
plugins/manager/lang/de_de.lang
plugins/manager/lang/en_gb.lang
plugins/manager/lib/yform/manager.php
plugins/manager/lib/yform/manager/dataset.php
plugins/manager/lib/yform/manager/table.php
plugins/manager/pages/data_history.php
plugins/manager/pages/data_import.php
plugins/manager/pages/table_edit.php

#44 
WIP .. Historie kann pro Tabelle aktiviert werden, und wird dann auch bereits erstellt. Aber es gibt noch keinerlei Ansicht der Historie.
@staabm Fände es klasse, wenn du schon mal drüber schauen könntest, was du von der Tabellen- und Klassenstruktur hältst.

Datensatz-Api und optionale Historie für Manager-Tables

---

plugins/manager/lib/yform/value/be_manager_relation.php

MySQL error if "NOT IN ()" -> empty vlaues
adjustments for relational table query - don't put "NOT IN" operator if there aren't any values.

check for empty values

---

lib/yform/value/datestamp.php

label in Feldbeschreibung ergänzen

---

plugins/geo/lib/yform_value_google_geocode.php

Zoom-Eingabe

---

plugins/geo/ytemplates/bootstrap/value.google_geocode.tpl.php

Zoom-Stufe auslesen

---

plugins/manager/lib/yform/value/be_table.php
plugins/manager/ytemplates/bootstrap/value.be_table.tpl.php

be_table improvements und Issue #387 behoben

---

plugins/manager/lib/yform/value/be_table.php

- Bug gefixt bei Row-Indizes wenn Zeilen entfernt und wieder hinzugefügt wurden
- Feld Validierung hinzugefügt

Bug fix + Validieriung hinzugefügt

---

lib/yform/value/date.php

Notice: Undefined index: format in .../redaxo/src/addons/yform/lib/yform/value/date.php on line 196

Fixed notice

---

lib/yform/value/time.php

ein time Feld als select im table manager wurde beim Bearbeiten immer auf 00:00:00 gesetzt.

fix for time field value, issue #245

---

plugins/docs/package.yml

Vorschlag für einheitlichen Standard

Doku/Hilfe-Tab rechts.

---

lib/yform/action/showtext.php
module/module_input.inc
module/module_output.inc

Sobald Markitup installiert ist, lässt sich textile nicht mehr installieren und der bisherige Code hat einen Fehler geworfen.

Installiertes textile addon abfragen

---

update.php

mysql bei Update aus datestamp-Feld entfernen

---

lib/yform/value/choice.php

Labels als Alternative beibehalten. 
close #561

choice: value auch in E-Mails ausgeben

---

lib/yform/value/upload.php

beim importieren von tablesets ist mir aufgefallen dass der Upload nicht funktioniert. Bitte bei Gelegenheit prüfen ob meine Änderungen fürs Frontend so funktionieren

upload bugfix

---

ytemplates/bootstrap/value.upload.tpl.php
ytemplates/classic/value.upload.tpl.php

Dateiendungen im accept-Attribut mitgeben

---

plugins/manager/lib/yform/manager/collection.php

closes #666
Die folgenden Methoden liefern ein neues collection-Objekt: `filter`, `slice`, `shuffle`, `sort`.
`map` liefert hingegen ein normales Array. Die collections sind zurzeit darauf beschränkt, dass die Values Objekte der dataset-Klasse sein müssen. Bei `map` kann aus der Callback aber ja beliebiges kommen, daher ein Array und keine Collection.
Bei `split` und `chunk` kommen zurzeit ein Array von Arrays raus (multidimensional). Hier bin ich mir nicht sicher, die inneren Arrays könnten theoretisch auch wieder Collections sein. Aber glaube würde es so lassen bei Arrays. Hast du dazu eine Meinung, @tbaddade?
`take` habe ich nicht implementiert. Glaube nicht, dass man die so oft braucht, und kann man auch leicht über `slice` lösen.
`take(3)` => `slice(0, 3)`
`take(-3)` => `slice(-3)` …

Collection: Weitere nützliche Methoden

---

ytemplates/classic/value.checkbox.tpl.php

Das classic-Template hat einen Fehler:
getValue() == $value ? ' checked="checked"' : '' ?>
muss in
getValue() == 1 ? ' checked="checked"' : '' ?> geändert werden
also anstatt "$value" eine "1" einfügen
und im HTML-Teil muss value="\<?php echo $value; \?>" in value="1" geändert werden

Correct value.checkbox.tpl.php in classic-Template

---

ytemplates/classic/value.choice.select.tpl.php

value.choice.select.tpl.php fehlt im classic-Template... habe dieses Template einfach aus dem bootstrap-template kopiert und den umschliessenden \<div>-Tag in einen \<p>-Tag geändert....

value.choice.select.tpl.php für classic-Template

---

ytemplates/bootstrap/value.mediafile.tpl.php

closes: https://github.com/yakamara/redaxo_yform/issues/708

Mediaelement TPL Error :: $this-getElement

---

lib/yform/value/choice.php
ytemplates/bootstrap/value.choice.check.tpl.php
ytemplates/bootstrap/value.choice.select.tpl.php
ytemplates/classic/value.choice.select.tpl.php

Die Ids der Choice Fields wurden bis dato nicht ausgegeben.

Choice Field Ids

---

plugins/manager/lib/yform/value/be_manager_relation.php

vorbereitende Maßnahme für #89

be_manager_relation: integer als Datentyp ermöglichen

---

lib/yform/value/choice.php

https://github.com/yakamara/redaxo_yform_docs/issues/142

Hinweis auf Nutzung von 0,1 statt false und true

---

plugins/manager/assets/manager.js

remove debug outputs

---

plugins/email/install.php
plugins/email/pages/index.php

Bezieht sich auf FriendsOfREDAXO/developer#52 (PR: FriendsOfREDAXO/developer#82)
Closes #823

E-Mail-Templates updatedate Spalte hinzufügen

---

plugins/email/lib/yform_action_tpl2email.php

Sollte BC-kompatibel sein. Ungetestet
closes #396

E-Mail als 3. Feldparameter erlauben

---

plugins/manager/lib/yform/value/be_table.php
plugins/manager/ytemplates/bootstrap/value.be_table.tpl.php
plugins/manager/ytemplates/classic/value.be_table.tpl.php

um Yform-Inline-Tabellen zu unterstützen. Siehe #820

name-Attribut der Felder von Feld-ID zu Feld-Name ändern

---

lib/yform/value/text.php

notice als optional markiert, prepend und append hinzugefügt

getDescription() aktualisiert

---

docs/demos.md
docs/formbuilder.md
docs/intro.md
docs/plugins.md
docs/table_manager.md
docs/yorm.md

Überarbeitung von Schreibfehlern und leichte textliche Anpassungen (bessere Lesbarkeit)

Rechtschreib-Korrekturen in der Dokumentation

---

docs/demos.md

via @rotzek aufgefallen. Danke.

Korrektur hidden-Feld

---

lib/yform/value/datetime.php

Verhalten angleichen an date-Feld

negatives Offset für datetime-Jahrfeld ermöglichen

---

docs/formbuilder.md

Danke @dergel für die Erläuterungen

upload-Feld-Verhalten im Frontend erläutern

---

lib/yform/value/choice.php

choice: offer varchar or tinyint as db_type

---

docs/table_manager.md

Wie im gleichen kapitel kurz zuvor beschrieben
https://github.com/yakamara/redaxo_yform/pull/904/files#diff-b7334e02ddcb7c297b75724fcad34089L21

„Aktiv“ beschreibung korrigiert

---

lib/yform/value/recaptcha_v3.php
ytemplates/bootstrap/value.recaptcha_v3.tpl.php
ytemplates/classic/value.recaptcha_v3.tpl.php

Fügt reCaptcha V3 / Invisible Captcha hinzu. Funktioniert genau gleich wie normals recaptcha, nur das die Keys explizit für V3 generiert werden müssen und das neue Feld heisst "recaptcha_v3".

add recaptcha v3

---

.github/workflows/phpstan.yml
composer.json
composer.lock
phpstan-baseline.neon
phpstan.neon.dist

publish yform classes on packagist.org for re-use in other addons.

---

lib/yform/value/choice.php

Mit der Anpassung kann man auch eine Userfunc im Tablemanager eintragen, um die Choice Elemente zu definieren. Die Userfunc muss ein json zurück geben.

Choice Elemente im Tablemanager als Callable

---

docs/formbuilder.md

Choice zusätzliche E-Mail-Templates-Angaben erwähnen

---

lang/de_de.lang
lib/yform/value/uuid.php

Erste Version.
Hintergrund:
https://www.davidangulo.xyz/advantages-and-disadvantages-of-uuid/
Generator-Funktion kopiert von
https://www.uuidgenerator.net/dev-corner/php 
Alternativ:
https://github.com/ramsey/uuid
Infos zur Performance:
https://mariadb.com/kb/en/guiduuid-performance/
Arbeiten mit UUID auf der Datenbank:
https://www.geeksforgeeks.org/uuid-function-in-mysql/

neues value: uuid

---

plugins/manager/lib/yform/manager/field.php

Warning | Undefined array key "relation_table" fix #1098

---

lib/yform/value/date.php
lib/yform/value/datetime.php

bisher wurden 20 Jahre zur Auswahl angeboten wenn Start- und Endjahr gleich waren.

fix date und datetime field when yearStart = yearEnd (only one year in select options)

---

docs/03_table_manager.md

da mittlerweile Redactor (3) empfohlen wird.

redactor 2-Hinweis korrigieren

---

docs/03_table_manager.md

Danke @tbaddade für den Hinweis in #1164

Fix Tippfehler Redactor

---

plugins/email/pages/index.php
plugins/manager/lib/yform/manager.php
plugins/manager/pages/table_edit.php
plugins/rest/pages/access.php
plugins/rest/pages/token.php

Mit der Helferklasse werden Buttons einfacher klickbar. Gelbe Markierung im Screenshot ist nur beispielhaft.

use rex-link-expanded for icon buttons

---

lang/de_de.lang

"Vergleichsart" => "Fehlermeldung, wenn..."

---

plugins/manager/install.php

remove debug-Ausgabe bei Update auf 4.0 (roles)

---

docs/07_formbuilder.md

answertext entfernt (docs)

---

lib/yform/value/generate_key.php

damit ich nicht gezwungen bin, den Key in der db zu speichern...

generate_key: "no_db" hinzugefügt

---

plugins/manager/lib/yform/manager/query.php

Tippfehler in query.php

---

plugins/manager/lib/yform/manager.php

closes https://github.com/yakamara/redaxo_yform/issues/1292
ungetestet

add stacktrace to error message to ease debugging

---

lib/yform/value/date.php
lib/yform/value/datestamp.php
lib/yform/value/datetime.php

Werte werden besser abgefangen

Datetime format history

---

package.yml

fixes: https://github.com/yakamara/redaxo_yform/issues/1310

set min. PHP Version to 7.4

---

docs/07_formbuilder.md

Dass das noch niemand benutzt und gemeldet hat :'D

docs Tippfehler hidden-Feld

---

lang/de_de.lang
lang/en_gb.lang
lib/yform/value/date.php
lib/yform/value/datestamp.php
lib/yform/value/datetime.php
lib/yform/value/time.php

closes #1180 
Diese Einstellung wird nur für die Ausgabe in der Listen-Übersicht und in der View-Ansicht verwendet

Anzeigeformat um Notice ergänzt

---

docs/03_table_manager.md

Doku customfunc angepasst

---

docs/02_email.md
docs/07_formbuilder.md

Doku. E-Mail Validierung auf type geändert

---

ytemplates/bootstrap/value.signature.tpl.php

Ergänzt die Funktionalität im Frontend (Thx @eaCe ) und für Touch Devices.

Frontend fix und Touch devices capabilities

---

plugins/manager/lib/yform/manager/table/api.php

API Performance verbessert

---

docs/07_formbuilder.md

Ergänzung für Formatierungen von Date Feldern als native Datepicker sowie die Attribut-Schreibweise in Pipe-Definitionen

Date und Attribute

---

docs/07_formbuilder.md

Doku: Update 07_formbuilder.md

---

lib/yform/value/upload.php

Upload-Value: JSON-Schreibweise-Eingabe im Table Manager durch Coldmirror-Feld erleichtern

---

lib/yform/value/choice.php

cache choice field getlistValues() dependent on table name

---

plugins/manager/lib/yform/value/be_link.php
plugins/manager/lib/yform/value/be_media.php

fixes: https://github.com/yakamara/yform/issues/1474

InUse Link mit CSRF

---

lib/yform/action/callback.php

siehe hier als Fehlerbeispiel
(https://github.com/yakamara/redaxo_yrewrite/issues/564)

Callback funktionierte nicht richtig, wenn kein Modus angegeben wurde

---

plugins/manager/pages/data_history.php

fixing history panel actions (links for "view" and "restore")

---

plugins/email/package.yml

should be released immediately!
fixes #1494

email plugin without perm allows access for EVERYONE

---

plugins/manager/lib/yform/manager/table/api.php

Export Tableset Ksorted 

---

plugins/manager/lib/yform/value/be_link.php

`be_link` Datentyp `int(10) unsigned` ermöglichen

---

docs/04_yorm.md

ref: https://github.com/yakamara/yform/pull/1456#pullrequestreview-1650345306

YORM-Doku: Beispiel für resetSelect()
