plugins/manager/lib/yform/manager/search.php
Ich bin vor ein paar Tagen auf das Problem gestoßen, dass die Suche nicht geht und musste eine schnelle Lösung finden.
Dann habe ich gesehen, dass es dabei nur um ein paar Klassennamen geht, die falsch benannt sind, danach ging es schon.
Was ich auch gesehen habe: Es gibt zu dem Problem hier auch schon länger eine Bug-Meldung: #31
=> Suchfunktion in Manager-Tabellen

ytemplates/bootstrap/value.radio.tpl.php
Damit man hier leichter arbeiten kann, sollte die Klasse radio zum Element hinzugefügt werden.
Ich würde hier noch ein SPAN-Tag vor das Label stellen, damit man mit input:checked + span {} den Radiobutton anderst stylen kann.
=> Radio klasse analog zum Checkbox-Template ergänzen

plugins/manager/lib/yform/manager.php
Wirft einen Fehler, wenn man den Formular-Code mit "default" als form_skin kopiert. Grund:
"default"-Template gibt's nicht mehr, ist jetzt "bootstrap".
=> default form_skin auf "bootstrap" ändern

plugins/manager/lib/yform/manager.php
Falschen action-Name korrigiert.
https://github.com/yakamara/redaxo_yform/issues/77
=> action von "email" auf "tpl2email" korrigiert

plugins/email/lang/de_de.lang
Hat mich schon immer irritiert, weil ich mir nie sicher war, ob Absender oder Empfänger gemeint war.
=> E-Mail-Templates: "Absender" statt "E-Mail"

ytemplates/bootstrap/value.checkbox.tpl.php
Für `input[type="checkbox"]` sind folgende Attribute erlaubt: `['required', 'disabled', 'autofocus']`
https://www.w3.org/TR/2012/WD-html-markup-20121025/input.checkbox.html
=> erlaubte attribute ergänzt

lib/yform/value/select_sql.php
Wenn für die Leeroption kein Text eingegeben wird, kommt [von hier](https://github.com/yakamara/redaxo_yform/blob/master/lib/yform/base_abstract.php#L77) `false` zurück. Die i18n Funktion [hier](https://github.com/yakamara/redaxo_yform/blob/master/lib/yform/value/abstract.php#L247) streckt daraufhin alle Viere von sich, weil sie einen string möchte und bool bekommt.
=> Text Leeroption auf string casten

plugins/manager/lib/yform/value/be_manager_relation.php
value.be_manager_relation.tpl.php l78 warning cause of array passed into htmlspecialchars() (popup (single))
set $valueName to correct value in be_manager_relation.php
=> be_manager_relation popup (single) warning

lib/yform/value/select_sql.php
Damit wird die Leeroption zuverlässig selektiert, wenn noch kein Wert ausgewählt ist.
=> 0 ist ein gülitiger Defaultwert

plugins/manager/assets/manager.css, plugins/manager/lib/yform/value/be_table.php, plugins/manager/ytemplates/bootstrap/value.be_table.tpl.php
dadurch ist es möglich die yform-builder Notation für be_table-Spalten zu verwenden.
Bsp.:  `text|title|Titel,textarea|text|Beschreibung,be_media|image|Bild`
=> be_table: yform value fields using added

plugins/manager/lib/yform/value/be_table.php, plugins/manager/ytemplates/bootstrap/value.be_table.tpl.php
ihr habt da teil entfernt die notwendig sind um REX_MEDIA und REX_MEDIALIST in be-table zu verwenden.
Probiert bitte folgende Spaltenbezeichnungs-Notation: 
`textarea|text|Textblock|||{"rows":"3","class":"redactorEditor2-text"}|,be_media|images|Bilder nach Textblock|1|1|`
=> be-table auf media und medialist erweitert

plugins/manager/lib/yform/value/be_manager_relation.php
getRelationTableFields hat bei extern verknüpfter 1:n Tabelle mit Verknpüfung auf die Datentabelle selbst nicht funktioniert.
=> 1:n Verknüpfung bei externer Tabelle

ytemplates/bootstrap/value.google_geocode.tpl.php, ytemplates/bootstrap/value.radio.tpl.php, ytemplates/bootstrap/value.select.tpl.php, ytemplates/bootstrap/value.textarea.tpl.php, ytemplates/bootstrap/value.upload.tpl.php
In den Feld-Templates für captcha, google_geocode, radio, select, textarea und uplaod die Klasse yform-element ergänzt. Die Klasse ist in den anderen Feldern jeweils enthalten. Betrifft nur ytemplate/bootstrap. Bezug: #443
=> Fehlende Klasse "yform-element" in mehreren Feld-Templates ergänzt

install.php, lib/yform/value/captcha.php, lib/yform/value/captcha_calc.php, update.php
Gibt es doch eigentlich keinen Grund für, den Ordner zu kopieren, oder?
(Das macht aktuell in YDeploy Probleme, da wir dort den data-Ordner von yform in shared haben, wegen der Uploads und dadurch fehlen teilweise die Fonts.)
=> Data-Ordner (fonts) nicht mehr kopieren

plugins/email/install.php
Einzige YForm Tabelle, die beim Upgrade auf 3.0 nicht konvertiert wird. Das war bestimmt keine Absicht, oder?
=> Tabelle in utf8mb4 konvertieren

ytemplates/bootstrap/value.mediafile.tpl.php, ytemplates/classic/value.mediafile.tpl.php
Das Upload-Dialogfeld hat bisher unabhängig von im yForm mitgegebener Typ-Begrenzung IMMER eine Auswahl aller Dateien ermöglicht ("all types *.*).
Mit dieser Erweiterung wird das Dialogfeld entsprechend der gewünschten Filetypes bereits bei der Usereingabe angepasst und lässt nur die Eingabe des gewünschtes Typs zu!
Die Änderung wurde einmal im yTemplate "bootstrap" und einmal in "classic" hinzugefügt...
=> Upload-Dialogfeld per Filter auf gewählte Filetypes begrenzen

plugins/email/pages/index.php
Aktuell stehen nur die Namen der Datenbankspalten da...
=> reply_to und reply_to_name in der Listenansicht ausblenden

plugins/manager/assets/widget.js
setYFormDataset triggered Event `rex:YForm_selectData`
deleteYFormDatasetList triggered Event `rex:YForm_deleteData`
Mit der vorherigen Variante konnte ich im Opener-Dokument nicht auf den Event rex:YForm_selectData reagieren. Mit dieser Variante klappt es.
Ausserdem habe ich den Trigger am Ende des Skripts eingefügt, damit man auch auf die ggf. veränderten Daten im Quell-Element reagieren kann.
=> Patch: Zugriff auf Events erlauben

plugins/manager/ytemplates/bootstrap/value.be_manager_inline_relation.tpl.php, plugins/manager/ytemplates/bootstrap/value.be_manager_relation.tpl.php
See **Warning** at https://www.php.net/crc32:
> Because PHP's integer type is signed many crc32 checksums will result in negative integers on 32bit platforms. On 64bit installations all crc32() results will be positive integers though.
> 
> So you need to use the "%u" formatter of sprintf() or printf() to get the string representation of the unsigned crc32() checksum in decimal format.
=> Prevent negative integer results for crc32-call

ytemplates/bootstrap/value.checkbox.tpl.php
einheitlich zu choice - wird benötigt, um checkbox-inputs per CSS "stylen" zu können.
=> add formhelper to checkbox value tpl

plugins/manager/pages/data_edit.php
Die Verwendung von `rex_be_controller::getCurrentPage()` erlaubt das direkte Einbinden der data_edit Ansicht in einem eigenen Addon, bzw. weiterhin wie gewohnt in YForm.
=> Page Parameter auf aktuelle Seite

plugins/manager/lib/yform/manager.php
Aus irgendeinem Grund ist das ursprüngliche Repo verschwunden, Start war ursprünglich hier. #843
@christophboecker hat hier wohl die sauberste Variante geliefert um den Tabellentitel anzusprechen und sofern man möchte auch im eigenen Addon in der boot.php wieder auszublenden. Snippet wäre dann dieses hier:
```php
rex_extension::register('YFORM_MANAGER_DATA_PAGE_HEADER', function($ep) {
//Sofern nur bei einer Tabelle gewünscht
if ($ep->getParam('table') === 'rex_product') {
$ep->setSubject('');
}
}, rex_extension::LATE);
```
Wäre schön, wenn der PR es in die nächste Version schafft ;)
=> Tabellentitel per EP

lib/yform/validate/empty.php
in der REDAXOhour wurde erwähnt dass man an dieser stelle mehrsprachig arbeiten kann.
**ich vermute** das geht mit dem regulären translate prefix... daher an dieser stelle auch die Notiz einblenden, die wir im core überall an solchen feldern haben
=> added notice for "empty" validation

plugins/manager/lib/yform/manager.php
Die Tabellenbeschreibung ist eigentlich Teil des Titels, sprengt aber den Rahmen des Platzes bei Popup-Fenster. Lösung: wenn Popup, dann keine Tabellenbeschreibung ausgeben.
Wurde beschrieben hier #855. 
Die Grundfuntionalität für Popup-Fenster, ist im Addon "be_style". Man kann draüber streiten, ob "be_style" zu große Titel abfangen müsste oder ob "yform" sich an die Fähigkeiten und Limitierungen von "be_style" anpassen muss.  Mein Vorschlag hiermit: in "yform" anpassen, weil es einfach und schnell geht.
=> Falls Popup-fenster: verkürzter Titel

lib/yform/value/date.php
Betrifft Issue #860. Da wird beschrieben, dass eine Eingabe im Suchfenster zu einer ungültigen SQL-Afrage führt, die nicht abgefangen wird. Die Änderungen betreffen die Methode `getSearchFilter`, die den fehler baut. Mit den Änderungen wird erreicht:
* Ungültige Eingaben werden zu `WHERE FALSE`, somit ist der SQL-Fehler vermieden
* Zusätzlich wurden die Auswertungsmöglichkeiten durch flexiblere Suchbegriffseingabe verbessert 
* Eingaben dürfen etwas laxer sein, was die Leerzeichen anbelangt.
Die Änderungen im Detail:
* Bei allen Eingaben dürfen die Elemente DD und MM jetzt auch 1-stellig eingegeben werden ( 01 und 1 sind gleichwertig)
* bei allen Eingaben darf das Element YYYY jetzt auch 2-stellig eingegeben werden. 2-stellige Jahreszahlen werden um 20 ergänzt (19 und 2019 sind …
=> Suchfunktion: Auswertung verbessert, SQL-Fehler vermieden #860

plugins/manager/lib/yform/manager.php
In XForm war es möglich, dass ein Result-Set im be_manager_relation Popup komplett gelöscht werden konnte. Es gibt meiner Meinung nach viele Anwendungsfälle dafür.
=> Massenlöschung in be_manager_relation Popup erlauben.

plugins/manager/lib/yform/value/prio.php
Ermöglicht u.a. auch die Aktivierung der Live-Suche mittels
`{"class": "form-control selectpicker","data-live-search": "true"}`
closes: https://github.com/yakamara/redaxo_yform/issues/682
Vorher: 
Nachher:
=> Attribute für PRIO-Feld

lib/yform/value/showvalue.php
@dergel ich brauche das gerade, da auf dem Feldtyp ein Index der Datenbank liegt und das geht nicht mit `text`. Hätte es deswegen in der 3.4 drin.
Hoffe, das war's jetzt an Störungen von mir ;)
=> showvalue - varchar erlauben

docs/yorm.md
für mich sind hier zu viele überschriften.. inbesondere liefern die 2 headlines keinen inhaltlichen mehrwert, da sie im großteil sich gegenseitig wiederholen (mit fachwörtern die viele redaxo user gar nicht kennen -> es schreckt ab).
habe eine in meinen Augen überflüssige entfernt
Vorher:
Nachher:
=> remove superflous headline

docs/formbuilder.md
Im Beispiel wird das Label "wert2" verwendet, welches aus dem Beispiel von compare übernommen wurde, jedoch muss bei diesem Validate an der Stelle ein Wert übergeben werden.
=> Falscher Parameter in compare_value Beispiel korrigieren

plugins/manager/lib/yform/manager/query.php
Die Methode durchsucht Spalten mit kommaseparierten Werten.
```php
// Entweder kann nach einem einzelnen Wert gesucht werden
$query->whereListContains('my_column', 5);
$query->whereListContains('my_column', 'my_value');
// Oder mit einem Array von Werten, ob mindestens einer davon enthalten ist
// dann aber nur mit integer-Werten!
$query->whereListContains('my_column', [3, 5, 9]);
```
=> query: neue Methode whereListContains()

docs/table_manager.md
Es sollte nicht 2 mal "!=" stehen, sondern nur einmal. Statt dessen fehlte "==".
=> Tippfehler beseitigt

assets/yform-formbuilder.css, lib/yform.php
- New line zu `<br>` umschreiben in Beispielen
- Code als inline-block darstellen
Links:
- Löst folgendes Problem: https://friendsofredaxo.slack.com/archives/C1BAXLN2F/p1597916533016100?thread_ts=1597916043.014600&cid=C1BAXLN2F
- Tritt auf da New Line nicht angezeigt wird mit dem aktuellen CSS: https://github.com/yakamara/redaxo_yform/blob/dec5f746d4945ca240daf3c6499fd9df68f1e78c/lib/yform/value/hidden.php#L42
=> Style von Beispielen im Formbuilder verbessern

plugins/manager/lib/yform/manager/dataset.php
fixes: https://github.com/yakamara/redaxo_yform/issues/950
Class into /lib - folder of project addon
```php 
class my_ycom {
public static function getTheUser() {
$ycom_user = rex_ycom_auth::getUser();
$subject = rex_ycom_auth::getUser()->getValue('login');
return $subject ;
}
}
```
Example for project boot.php
```php
rex_extension::register('PACKAGES_INCLUDED', static function () {
if(!rex::isBackend() && rex_ycom_auth::getUser())
{
rex_extension::register('YCOM_HISTORY_USER', 'my_ycom::getTheUser');   
}
});
```
=> Adds EP to overwrite History user

plugins/manager/ytemplates/bootstrap/value.be_table.tpl.php
Das Feld zeigt keinen Eintrag `0` an. Mit der Anpassung wird der Eintrag 0 korrekt angezeigt.
=> Eintrag 0 anzeigen

plugins/manager/lib/yform/manager/query.php
the only valid strings for this var are `AND` or `OR`, so no multibyte-magic involved
=> simply use `strtoupper` instead of the mb-ext equivalent

plugins/manager/lib/yform/manager.php
Vorschlag für einen neuen EP. In der *manager.php* wird ja u.a die Liste zusammengestellt. Dabei werden je nach Parametrisierung und User-Context (isAdmin) auch Buttons in die Titelteile der Datentabelle geschrieben. Ich hab vermisst, dort auch mit einfachen Mitteln eigene Button einzubauen. Z.B. eine Funktion einzuhängen, die mir auf Klick die Tabelle beim Testen wieder in einen Basiszustand zurückversetzt. Ja, kann man evtl. auch per YFORM_DATA_LIST_GRID hinbekommen, ist aber nicht so schön.
Dazu müsste die Reihenfolge der Bearbeitungsschritte etwas umgestellt und der EP-Aufruf hinzugefügt werden. Bisher ist die Abfolge
-    Erstelle die $table_links
-    Ausgabe der $table_links
-    Erstelle die $field_links
-    Ausgabe der $field_links
Was ich geändert habe in
-    Erstelle die …
=> Neuer EP YFORM_DATA_LIST_LINKS hinzugefügt

plugins/manager/boot.php, plugins/manager/lib/yform/manager.php, plugins/manager/lib/yform/manager/table.php, plugins/manager/pages/table_edit.php, plugins/manager/pages/tableset_export.php
Kein großes Ding, aber die Berechnung des Labels (rotes Oval) ist uneinheitlich.
In der Auflistung der Tabellen für den Export wird nur der *table_name* (z.B. rex_tabelle) angezeigt, es sei denn es gibt einen .lang-Eintrag  `rex_tabelle = Label`. Der eigentliche Tabellennamen (Feld *name*) wird ignoriert.
In der Editierliste ist es genau anders; es wird ausschließlich der Wert im Feld name* ("Beschreibung") herangezogen. Das ist plausibel, da es ein Pflichtfeld ist, aber Inghalt ist eben oft nur der Tabellennamen (z.B. rex_tabelle). Der wird dann aber mangels führendem `translate:`nicht via .lang-Eintrag übersetzt. 
|  table_edit | table_export  | Seitenleiste |
| --- | --- | --- |
|![grafik](https://user-images.githubusercontent.com/10065904/108703921-9207b200-750b-11eb-8c94-27e36078cb08. …
=> Tabellennamen für Export und Edit-Liste optimiert

package.yml
um nach der Installation der github-version auch nach Wochen noch zu erkennen, dass es sich nicht um einen offiziellen Release handelte.
=> version bump 3.5.0 Update package.yml 

plugins/manager/lib/list.php, plugins/manager/lib/yform/manager/query.php
Wie in Issue #1070 diskutiert muss der Alias hinzugefügt werden, um bei Queries mit Join-Anteilen automatisch eingefügte Felder (meist 'id') eindeutig zu machen.
Details und warum es auffiel stehen im Issue. Betrifft die neue Klasse rex_yform_list und die Klasse rex_yform_manager_query
=> YF4beta2: Alias hinzufügen

plugins/manager/lib/yform/value/be_user.php
Wurde nur übersetzt wenn Option "Wert setzen: immer" gewählt war. Ansonsten hardcore.
=> update be_user translation

plugins/manager/lib/yform/manager.php
Aufgefallen bei Joins über den neuen EP YFORM_DATA_LIST_QUERY: Das Feld "id" muss eindeutig gemacht werden über den Alias. Da Instanzen von rex_yform_manager_query in Where-Statements den Alias aus gutem Grunde nicht automatisch hinzufügen, muss der Alias ausdrücklich im `->where` angegeben werden. Sieht so aus als ob es nur diese eine Stelle im Manager ist, an der so eine Situation entsteht.
=> YF4beta2: Fehlender Alias im Manager ergänzt

plugins/manager/lib/yform/manager/query.php
`$query->leftJoinRelation ($feldname)` baut einen LEFT-Join auf oder auch **nicht** (wenn be_manager_relation vom Typ 4 oder 5 ist). Der PR behebt das Problem
siehe #1082
=> YOrm-Query: leftJoinRelation

plugins/manager/lib/list.php
Wie schon in #1080 beschrieben schlage ich zwei weitere Methoden für die rex_list bzw. rex_yform_list vor. In rex_list sind die Änderungen akzeptiert und gemerged. Dieser PR übernimmt den finalen Code aus rex_list 1:1 für rex_yform_list.
=> rex_yform_list: setColumnPosition/getColumnPosition

plugins/manager/lang/de_de.lang
Kompromiss-Vorschlag zu #1044 - es gibt kein besseres Wort für `leeren`, weil das vorangehende "Tabelle" von einer anderen Stelle kommt. 
Aber die Warnung und Erfolgsmeldung kann man entsprechend präzisieren.
closes #1044
=> löschen statt leeren

lib/yform.php
An mehreren Stellen (z.B. https://github.com/yakamara/redaxo_yform/blob/master/lib/yform/action/db.php#L27) wird  `$this->params['Error-Code-InsertQueryError']` verwendet.
Dieser param fehlt aber in yform.php
Nur "Error-Code-QueryError" existiert als yform objparam:
https://github.com/yakamara/redaxo_yform/blob/master/lib/yform.php#L60
=> fehlenden objparam hinzugefügt

lib/yform/action/redirect.php
Wenn in einem Formular eine Inline Relation verwendet wird, gibt es den entsprechenden Value als Array im value_pool.
Das knallt bei urlencode. Die drei zusätzlichen Zeilen verhindern dies.
=> Oops bei Formularen mit inline Relation verhindern

plugins/manager/install.php
Beim Update von 4.0.0-beta6 auf 4.0.0 (final) kommt ein SQL-Fehler.
Wenn ich manuell in der Zeile mit ID=25 den `type_name` von `float` auf `number` setze, bricht er bei der nächsten Zeile 26 ab. Selbes Problem. Test der SQL-Abfrage im Adminer zeigt: `default` muß in Backticks weil in SQL ein reserviertes Wort.
=> Update auf 4.0: Backticks um 'default' in SQL-Abfrage zur Feldänderung

plugins/manager/lib/yform/value/be_manager_relation.php
> trim(): Passing null to parameter #1 ($string) of type string is deprecated
PHP 8.1
=> trim(): Passing null to parameter #1 ($string) of type string is deprecated

plugins/manager/lib/yform/manager/field.php, plugins/manager/lib/yform/manager/table.php
Mit PHP 8.1 kommen diese Deprecated-Meldungen:
> During inheritance of ArrayAccess: Uncaught ErrorException: Return type of rex_yform_manager_table::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
Aktuell werden die Meldungen im Rex-Autoloader stummgeschaltet, das möchte ich aber eventuell ändern.
Alternativ zu den Attributen könnte auch der richtige Return-Type hinzugefügt werden. Ist aber problematisch in einem Minor-Release.
Die Attribute funktionieren auch in PHP 7, dort sind es ja einfach nur Kommentare.
=> ReturnTypeWillChange-Attribut nutzen

plugins/manager/scss/manager.scss
Sorthandle gefixed und Styles für be_relation/inline hinzugefügt:
Vorher/Nachher:
=> style: fix sorthandle, update dark styles for be-relation-wrapper

plugins/manager/lang/de_de.lang, plugins/manager/lib/yform/manager.php
Nutzer sollten noch mal darauf hingewiesen werden, dass hier alle gefunden Datensätze bearbeitet werden. 
Es ist schon vorgekommen, dass versehentlich durch Nutzer alle Datensätze überschrieben wurden.
=> Warnung bei Massenbearbeitung

lib/yform/action/email.php
Datein aus email_attachments im value_pool werden als Anhang versandt. (Äquivalent zu tpl2email)
=> add email_attachments from value_pool as attachments

lib/yform/validate/preg_match.php
count(): Argument #1 ($value) must be of type Countable|array, null given
=> fixed type error: use is_countable() in validate preg_match

plugins/manager/lib/list.php
mit PHP 8.1 sind NULL-Parameter on str_replace nicht mehr zulässig (Warnung wg. deprecated). Das passiert z.B. wenn ein Feld vom Typ be_manager_relation zwar als YForm-Tabellenfeld (z.B. xyz) existiert, aber keine Entsprechung in einem real existierenden Feld in der Datenbank hat. Dann ist das Feld xyz als Tabellenfeld in der Liste vorhanden, aber $this->getValue('xyz') liefert null. Typecast auf "string" führt wieder zum gewohnten Ergebnis.
=> Für PHP8.1: NULL-Value in str_replace vermeiden

plugins/manager/lib/yform/manager/query.php
Folgender Code führt zu einer Exception:
```php
$result = \rex_yform_manager_query::get('rex_geolocation_mapset')
->alias('a')
->joinRelation ('layer','b')
->select('a.*')
->select('b.*')
->findId(1);
```
```
Error while executing statement "SELECT `rex_geolocation_mapset`.* FROM `rex_geolocation_mapset`
INNER JOIN `rex_geolocation_layer` ON FIND_IN_SET(`rex_geolocation_layer`.`id`,
`rex_geolocation_mapset`.`layer`) WHERE `id` = :p1 LIMIT 1" using params {"p1":1}!
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous
```
Was funktioniert ist ein explizietes Where mit Tablealias im Feldnamen
```php
$result = \rex_yform_manager_query::get('rex_geolocation_mapset')
->alias('a')
->joinRelation ('layer','b')
->select('a.*')
->select('b.*') …
```
=> In der Query-Klasse findId/findIds mit Table-Alias ausführen

package.yml
Im aktuellen Release 4.0.2 scheint der Ordner `.tools/vendor` mit gezipped worden zu sein.
```bash
marcel@matzel-linux:~/$ du -hs addon_yform_4.0.2/yform/
39M	addon_yform_4.0.2/yform/
marcel@matzel-linux:~/$ du -hs addon_yform_4.0.2/yform/.tools/vendor/
36M	addon_yform_4.0.2/yform/.tools/vendor/
```
fixes https://github.com/yakamara/redaxo_yform/issues/1254
=> ignore `.tools/vendor` for release

module/module_output.inc
Die aktuelle Schreibweise funktioniert nicht, sollte das Formular mal eingebunden werden. Das Ziel ist dann immer der eingebundene Artikel.
=> Modul :: form action aktuellen Artikel ermitteln

lib/yform/validate/type.php
E-Mail Adressen wie hänßchen@aus-dem-häußchen.de werden von Validate type email wegen der Umlaute abgelehnt. Tests mit filter_var(..., FILTER_VALIDATE_EMAIL) haben das gleiche Ergebnis ergeben. Daher hier ein Vorschlag, wie die Umlaute als korrekt validiert werden.
Ich bin kein Regexprofi, daher gerne nochmal anschauen :-)
=> Type email und url für DE-Umlaute erweitert

plugins/manager/boot.php, plugins/manager/lib/yform/manager/dataset.php
Mit dieser Funktion könnte man beim Speichern von Datensätzen die history abschalten.
Beispielsweise für cronjobs, die sehr häufig Daten überschreiben und dadurch sehr viele history Daten produzieren.
https://github.com/yakamara/redaxo_yform/issues/1307
=> dataset save - add history enable/disable feature

lib/yform/value/fieldset.php
Wenn die Keys nicht angegeben werden, verwendet Choice Zahlen als Indexe. Fieldset erwartet jedoch den Value-String.
=> Keys der Optionen fehlen

plugins/manager/ytemplates/bootstrap/value.be_manager_relation.tpl.php
Da sind wohl mal i18n-Bezeichner angepasst worden und einer wurde vergessen. Das sieht im HTML so aus:
Mit Korrektur durch diesen PR wird es
=> i18n-Namen korrigiert

plugins/manager/lib/yform/manager.php
=> neue Methode um eine Url zum Datensatz zu erhalten

plugins/manager/lib/yform/manager/collection.php, plugins/rest/lib/rest/route.php
`rex_yform_manager_collection` erbt von `SplFixedArray`. Und `SplFixedArray` hat früher `Iterator` implementiert, seit PHP 8.0 aber `IteratorAggregate`. Daher existiert seit PHP 8 die Methode `current` nicht mehr.
PR ungetestet!
=> rex_yform_manager_collection: Methode current existiert in PHP 8 nicht mehr

plugins/manager/pages/data_import.php
In If-else überprüfen ob ID im CSV leer oder 0 ist und in dem Fall Insert statt Update ausführen.
Damit klappen Daten-Imports mit neuen Inhalten (also ohne bereits existierende ID) auch wieder.
=> CSV-Import: $id has to be an integer greater than 0, but "" given #1209

lib/yform/value/uuid.php
Auslöser für diesen PR ist eine Diskussion im Slack. Daniel Springer (@medienfeuer) bemerkte, dass UUIDs beim erneuten Speichern das Datensatzes neu generiert wurden, was eigentlich nicht sein sollte. Auch Alex (@alxndr-w) hat das von Zeit zu Zeit.
Theoretisch ist der alte Code ok; trotzdem passiert es. 
Mein Lösungsvorchlag wäre, den Code näher an den Code von `rex_yform_value_generate_key` zu bringen. In dem Value wird der Key bereits in der Methode `preValidateAction` erzeugt. Vieleicht hilft es ja.
Und `enterObject` ist folglich auch angepasst. Hier wird zusätzlich eine Option ShowValue berücksichtigt, die ich dann auch angefügt habe.
=> Key-Generierung nach preValidateAction verlagert

plugins/manager/ytemplates/bootstrap/value.be_manager_inline_relation.tpl.php
Die Variable $id wird nirgends benutzt; auch nicht via `$this->parse('value.be_manager_inline_relation_form.tpl.php'...`. Scheint von einer alten Version über geblieben zu sein?
```php
$id = sprintf('%u', crc32($this->params['form_name'])) . random_int(0, 10000) . $this->getId();
```
=> Überflüssige Zeile $id=.. entfernt

lang/de_de.lang, lang/en_gb.lang, lang/es_es.lang, lang/sv_se.lang, lib/yform/validate/abstract.php
Es wurde zweimal dergleiche Wert an die i18n-Funktion übergeben und im Sprach-Label der .lang Datei wurde nur eine Variable benutzt.
=> fix validate type errormessage

plugins/manager/lib/yform/value/be_link.php
text ist wohl in den meisten Fällen überdimensioniert, int für einzelne IDs (wenn nicht multiple) ideal.
=> allow `varchar(196)` and `int` as `be_link` field definition

plugins/manager/lib/yform/manager/dataset.php
https://github.com/FriendsOfREDAXO/rexstan/issues/407#issuecomment-1474784809
this method is not meant for public use outside of yform
=> yorm: mark `dataset->setRelatedCollection()` as internal

docs/04_yorm.md, plugins/manager/lib/yform/manager/query.php
Auslöser des PR ist ein [Slack-Thread](https://friendsofredaxo.slack.com/archives/C1BAXLN2F/p1679900426442899).
Da HAVING im SELECT sowas wie WHERE im Gruppierungen ist, sind im Grunde die WHERE-bezogenen Teile dupliziert und im Namen um `having` erweitert. Die Teile werden an der passenden Stelle in die Query eingebaut.
Die `$this->params` werden als `$this->havingParams` separat geführt (sonst funktioniert `resetHaving()` nicht separat von `resetWhere()` und wäre sonst funktional ein Alias für `resetWhere` und vice versa. Entsprechend liefert getParams() nun das gemergte Array aus `$this->params` und `$this->havingParams`. Zur Unterscheidung haben havingParams `h` statt `p` als Marker.
`whereNested(..)` habe ich nicht übernommen. Das war mir zu heikel und der zwingende UseCase fiel mir …
=> Query um HAVING-Klausel erweitert

plugins/manager/lib/yform/value/be_manager_relation.php
**Vorher**
**Nachher**
closes https://github.com/yakamara/redaxo_yform/issues/1244
=> int(10) unsigned ergänzt, Vorbereitung für Foreign keys

plugins/manager/lib/yform/manager.php
review without whitespace changes: https://github.com/yakamara/redaxo_yform/pull/1430/files?w=1
---
should fix
```
Unable to rollback, no transaction started before
#0 .../src/addons/yform/plugins/manager/lib/yform/manager.php(507): rex_sql->rollBack()
#1 .../src/addons/yform/plugins/manager/pages/data_edit.php(20): rex_yform_manager->getDataPage()
#2 .../src/core/lib/packages/package.php(233): require('...')
#3 .../src/core/lib/be/controller.php(503): rex_package->includeFile()
#4 .../src/core/lib/util/timer.php(56): rex_be_controller::{closure}()
#5 .../src/core/lib/be/controller.php(504): rex_timer::measure()
#6 .../src/core/lib/be/controller.php(453): rex_be_controller::includePath()
#7 .../src/addons/yform/pages/index.php(3): rex_be_controller::includeCurrentPageSubPath()
#8 …
```
=> Manager: Fix "Unable to rollback, no transaction started before"

lib/yform/value/index.php
ungetestet - Alternativ bei $value noch ein trim() einbauen, statt umbauen.
=> index value - Führendes Leerzeichen entfernen

plugins/manager/lib/list_tools.php
=> Enable whitespace linkebreak for multiple validation params

lib/yform.php, ytemplates/bootstrap/errors.tpl.php
closes #240 Einleitender Text, z.B. `Ihre Angaben wurden noch nicht verarbeitet, bitte korrigieren Sie folgende Angaben:` und danach erst werden die Fehler aufgelistet.
=> Einleitender Text für Fehlermeldungen als objparam angeben können

docs/05_rest.md, plugins/rest/lang/de_de.lang, plugins/rest/lang/en_gb.lang, plugins/rest/lang/es_es.lang, plugins/rest/lang/sv_se.lang
Falls erwünscht. Ich hatte erst nach Fertigstellung des PRs gesehen, dass die Schreibweise `Tokens` auch gültig ist. Ich kenne den Plural von "Token" nur als "Token", nicht "Tokens".
=> Umbenennen Tokens -> Token

plugins/manager/lib/yform/manager/dataset.php
Die Typänderungen in der dataset-Klasse in https://github.com/yakamara/yform/commit/71c1438d0b54ef04dadea42e1cc470e5125bfc4c#diff-78fb339dacda30d7b4b4100e734511bdf9ea7107937e10583c1ee9a96e3e5065 waren so nicht sinnvoll/korrekt. Die sollten reverted werden. Falls rexstan da meckern, müssen wir schauen, wie wir es anders lösen.
=> dataset: Typangaben wieder korrigiert

plugins/manager/assets/widget.js
Fixes https://github.com/yakamara/yform/issues/1483
=> Update widget.js with rex:YForm_selectData

plugins/manager/lib/yform/manager.php
Ist das mal irgendwann kürzlich hintenüber gefallen?
Die TableDescription wird jedenfalls nicht (mehr) durch `rex_18n::translate` geschickt, was dann zu solchen Ausgaben führt:
Aus irgend einem Grund bin ich der Meinung, dass das mal anders war. Der PR behebt das Problem.
=> i18n-Translate für die Table-Description

plugins/manager/assets/widget.js, plugins/manager/lang/de_de.lang, plugins/manager/lang/en_gb.lang, plugins/manager/lib/var_yform_dataset.php, plugins/manager/ytemplates/bootstrap/value.be_manager_relation.tpl.php
YForm Widgets an den Core Widgets angepasst.
- `list` öffnet die Liste.
- `+` öffnet jetzt nicht mehr die Liste sondern man kann direkt einen Datensatz anlegen.
- `auge` öffnet den Datensatz in der Edit-Ansicht.
**Vorher**
**Nachher**
=> Widgets um Add und View Button ergänzt

plugins/manager/lib/yform/manager/table.php
Damit Drag & Drop von `yform_usability` auch für mehr als 30 Einträge funktioniert.
Es gibt gute Gründe, 100 Felder verwalten zu können und wer das macht, nimmt auch einen längeren Aufbau der Seite inkauf
Da es ohnehin keine Suchfunktion für Felder gibt, ist auch ohne `yform_usability` die browsereigene Suchfunktion somit nutzbar, ohne sich von Seite zu Seite zu kämpfen.
=> Table Manager: Feldverwaltung - 100 statt 30 Einträge zeigen

plugins/manager/boot.php, plugins/manager/install.php, plugins/manager/lang/de_de.lang, plugins/manager/lib/yform/manager/table.php, plugins/manager/lib/yform/manager/table/api.php, plugins/manager/pages/table_edit.php
Getestet mit Font-Awesome Icons
- rex-icon präfix wird automatisch gesetzt
- Wenn leer, wird das default icon genommen
- Natürlich mit rex_escape behandelt
Beispiel:
=> manager: Add Custom Icon for Tables 

lib/yform/value/uuid.php
=> Datensatz klonen: `Calling getId() on new, non-existing datasets is not allowed, check existence before by $dataset->exists()` beheben

lib/manager/manager.php
fix for #1425
Nach der sauberen Vorarbeit von @christophboecker schlage ich mal diesen Fix vor.
Weil ich gerade selbst dutzende Datensätze manuell im BE bearbeite und da nervt das!
change order of read "start"-params
Mir erscheint es logisch erst den "xxxx_start" Parameter auszuwerten und dann, wenn der nicht existiert den "start" zu nehmen.
Aber ob das überall passt, oder irgendwo anders Probleme erzeugt, weiß @dergel  am besten.
=> Mehrseitige Listen - beim erneuten Seitenaufbau kommt man immer auf Seite 1

lib/manager/search.php
Das Problem fiel mir bei einem Custom-Value auf. In einem einfachen Eingabefeld (text) sollten drei Begriffe (Breitengrad Längengrad Radius) für eine Umkreissuche eingegeben werden. Um das richtige Format sicherzustellen wurde auch ein Custom-Validator hinzugefügt. Der Validator macht seine Arbeit wie er soll. Aber die Query wurde dennoch (mit ungeeigneten Werten) gefüllt, was in einer Exception mündete.
Mit der hier eingebauten Abfrage nach Ausführen des Such-Formulars wird ohne Veränderung der Query abgebrochen. Somit werden Liste und Suchformular (nun mit Fehlermeldung) angezeigt.
-------
Falls sonst noch wer auf das Problem stößt: ich helfe mir jetzt mit doppelter Fehleranalyse: mit dem Custom-Validator für das Formular und dasselbe zusätzlich in value_class::getSearchFilter.
=> Validierungs-Ergebnis im Suchformular beachten

lang/de_de.lang, lang/en_gb.lang, lang/es_es.lang, lang/sv_se.lang, lib/yform/value/integer.php
+ adding example in help notice
=> adding possibility to search with comma separated list in integer and number fields
